# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073a1ec55f354c9fbf41375a1d7eab13a8de5f7bbfd52c6791c028dda4c663d36574399da70270afad23fdfc61fea1bf3a1eba3e7f590f237f5bcdf30c1e3f1e

test:
  secret_key_base: e6046c3b2a289396e17e87387f688d6adee6e10974300f9d1743ae92a33c2d97113d42eb05b1dbfed9be8c04465b9bef1434437b0c11257b32b4645f2e04cc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
